# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ef0dc391832b33f965a60ada17e067b3239f2481b76179a9465f6aead02eb5c70262806fa2b2a7ed1d438ff16a472b93400e97b79b2a47ca2a03dd1ca243218

test:
  secret_key_base: bf1322fc17552d75cbef46e99bb43ae0f3def605c4b3d1437b779fc60151d1ff4cbbe774b18960358a5feeda0d72080f4fdf4520c5637d92f9a9257eeb2c8231

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
